apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: paymybuddy
  labels:
    app: paymybuddy
    tier: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymybuddy
      tier: mysql
  template:
    metadata:
      labels:
        app: paymybuddy
        tier: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_DATABASE
          value: db_paymybuddy
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:            
            secretKeyRef: 
              name: paymybuddy-secrets
              key: mysql_root_password   
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mysql-volume
        - mountPath: "/docker-entrypoint-initdb.d"
          name: mysql-initdb
        readinessProbe:
          exec:
            command:
              - "sh"
              - "-c"
              - "mysqladmin ping -h 127.0.0.1 -u root -p$MYSQL_ROOT_PASSWORD"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-initdb
        configMap:
          name: mysql-init-script